### ISSUE TITLE
Lemmas

### ISSUE THREAD

**Issue by jcuenod** [chrisdrymon/greek-morph-tagger#5]
I'm assuming you tried this but I see you're not generating lemmas. What are your thoughts on generating lemmas?

**Comment by chrisdrymon** [comment]
I will totally be generating lemmas in the future; dependency as well. It's the next big functional update on my list. Maybe after I get a few resumes out!

**Comment by jcuenod** [comment]
Hey @chrisdrymon,

I thought I'd comment on the output I've looked at but then I realised it related to this issue. The results of this project are fantastic! A recurring error that I see is "και" coming up as an adverb. I actually think predicting roots would help with this because certain fixed forms would be perfectly predictable (unless και is parsed as an adverb). It also seems to have worked better on the apostolic fathers than on the lxx (but that's just a rough skim of random texts I happened to open).
